// <auto-generated />
using BackEnd.Dane;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Dane.Migracje
{
    [DbContext(typeof(PrzechowajDane))]
    [Migration("20221108130010_KoszykDodany")]
    partial class KoszykDodany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("BackEnd.Podmioty.Koszyk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KupiecId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Koszyki");
                });

            modelBuilder.Entity("BackEnd.Podmioty.KoszykPrzedmiot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoszykId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZwierzeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KoszykId");

                    b.HasIndex("ZwierzeId");

                    b.ToTable("KoszykPrzedmioty");
                });

            modelBuilder.Entity("BackEnd.Podmioty.Zwierze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Cena")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gatunek")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lokalizacja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.Property<int>("Plec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Typ")
                        .HasColumnType("TEXT");

                    b.Property<long>("Waga")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Wiek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZdjecieUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Zarezerwowane")
                        .HasColumnType("BOOL");

                    b.HasKey("Id");

                    b.ToTable("Zwierzeta");
                });

            modelBuilder.Entity("BackEnd.Podmioty.KoszykPrzedmiot", b =>
                {
                    b.HasOne("BackEnd.Podmioty.Koszyk", "Koszyk")
                        .WithMany("Przedmioty")
                        .HasForeignKey("KoszykId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Podmioty.Zwierze", "Zwierze")
                        .WithMany()
                        .HasForeignKey("ZwierzeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koszyk");

                    b.Navigation("Zwierze");
                });

            modelBuilder.Entity("BackEnd.Podmioty.Koszyk", b =>
                {
                    b.Navigation("Przedmioty");
                });
#pragma warning restore 612, 618
        }
    }
}
